env:
  browser: true
  es6: true
extends: eslint:recommended
parserOptions:
  sourceType: module
rules:
  indent:
  - error
  - 4
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - double
  semi:
  - error
  - always
  constructor-super: 1
  generator-star-spacing: 0
  no-this-before-super: 0
  no-var: 1
  object-shorthand: 0
  prefer-const: 2
  no-undef: 0
