env:
  browser: true
  es6: true
extends: eslint:recommended
globals:
  Vue: true
parserOptions:
  sourceType: module
rules:
  indent:
  - error
  - 4
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - double
  semi:
  - error
  - always
  constructor-super: warn
  generator-star-spacing: warn
  no-this-before-super: warn
  no-var: error
  object-shorthand: warn
  prefer-const: warn
  no-undef: error
