files:
  include: src/static/src/**/*.s+(a|c)ss
formatter: stylish
rules:
  indentation:
  - 2
  - size: 4
  nesting-depth:
  - 2
  - max-depth: 3
  quotes:
  - 2
  - style: double
  class-name-format:
  - 1
  - convention: hyphenatedbem
