files:
  include: 'src/static/scss/*.s+(a|c)ss'
  ignore: 'src/static/scss/vendor/*'
formatter: stylish
rules:
  indentation:
    - 2
    - size: 4
  quotes:
    - 2
    - style: double
  class-name-format:
    - 1
    - convention: strictbem
