version: "3.3"
services:
  laboratorium-ee-2019:
    build:
      context: .
      dockerfile: compose/Dockerfile
    volumes:
    - static:/static/
    - media:/media/
    - .:/code/
    environment:
      DJANGO_SECRET_KEY: "secret-key"
      DEBUG: "True"
      DJANGO_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/laboratorium-ee-2019"
      DJANGO_SETTINGS_MODULE: "src.settings.local"
      STATIC_ROOT: "/static/"
      MEDIA_ROOT: "/media/"
      GUNICORN_WORKERS: 2
      GUNICORN_BACKLOG: 4096
      GUNICORN_BIND: 0.0.0.0:8000
    working_dir: /code
    command: bash -c "compose/wait_for_development_db.sh && compose/create_development_db.sh && compose/install_npm_packages_if_required.sh && python3 manage.py migrate && gunicorn --config compose/gunicorn.conf src.wsgi"
    links:
    - "postgres:postgres"

  postgres:
      image: "postgres:latest"
      environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=laboratorium-ee-2019
      volumes:
          - postgres:/var/lib/postgresql/
  nginx:
    image: "registry.laboratorium.ee/nginx/nginx:latest"
    volumes:
    - static:/static/
    - media:/media/
    ports:
    - 8080:8080
    links:
    - "laboratorium-ee-2019:laboratorium-ee-2019"
    environment:
      PASS_TO: "http://laboratorium-ee-2019:8000"
      MEDIA_DIR: "/media/"
    depends_on:
    - laboratorium-ee-2019

volumes:
  static:
  media:
  postgres:
