version: '3'
services:

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    entrypoint: "pipenv run ./manage.py runserver"
    depends_on:
    - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "npm run start"

  db:
    image: postgres
