# Generated by Django 2.2.1 on 2019-05-28 08:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('main', '0004_jobofferindexpage_jobofferpage_newsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r_and_d_center_body',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='r_and_d_center_headline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specializations_headline',
            field=models.CharField(default='Specialisation headline default', max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CooperatorLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_logos', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperators_logos', to='main.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
