# Generated by Django 2.2.1 on 2019-05-28 13:47

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rodopassadvert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', wagtail.core.fields.RichTextField()),
                ('contact_pl', wagtail.core.fields.RichTextField(null=True)),
                ('contact_en', wagtail.core.fields.RichTextField(null=True)),
                ('address', wagtail.core.fields.RichTextField()),
                ('address_pl', wagtail.core.fields.RichTextField(null=True)),
                ('address_en', wagtail.core.fields.RichTextField(null=True)),
                ('how_we_work', wagtail.core.fields.RichTextField()),
                ('how_we_work_pl', wagtail.core.fields.RichTextField(null=True)),
                ('how_we_work_en', wagtail.core.fields.RichTextField(null=True)),
                ('privacy_policy', models.URLField()),
            ],
        ),
    ]
