# Generated by Django 2.2.1 on 2019-05-29 08:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='main.HomePage', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodopassadvert',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rodo_pass', to='main.HomePage', unique=True),
            preserve_default=False,
        ),
    ]
