# Generated by Django 2.2.1 on 2019-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190529_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='marked',
            field=models.BooleanField(default=False, help_text='If True, this article would be visible on HomePage and on top of NewsIndexPage'),
        ),
    ]
