# Generated by Django 2.2.1 on 2019-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_newspage_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='marked',
            field=models.BooleanField(default=False, help_text='If True, this article would be visible on HomePage and on top of NewsIndexPage. Only one article can be marked, so old one will be unmarked automatically.'),
        ),
    ]
