# Generated by Django 2.2.2 on 2019-06-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190612_1325'),
        ('main', '0011_auto_20190603_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_pages', to='projects.SpecializationPage'),
        ),
    ]
