# Generated by Django 2.2.3 on 2019-07-05 08:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190702_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferindexpage',
            name='recruitment',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy.html'), template='projects/blocks/tiles_list_with_arrows.html'))]),
        ),
        migrations.AlterField(
            model_name='jobofferindexpage',
            name='recruitment_en',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy.html'), template='projects/blocks/tiles_list_with_arrows.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='jobofferindexpage',
            name='recruitment_pl',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy.html'), template='projects/blocks/tiles_list_with_arrows.html'))], null=True),
        ),
    ]
