# Generated by Django 2.2.1 on 2019-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='subtitle_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='how_we_work_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='how_we_work_pl',
            field=models.TextField(null=True),
        ),
    ]
