# Generated by Django 2.2.1 on 2019-05-20 08:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_merge_20190515_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='challenge',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='challenge_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='challenge_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='process',
            field=wagtail.core.fields.StreamField([('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='process_en',
            field=wagtail.core.fields.StreamField([('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='process_pl',
            field=wagtail.core.fields.StreamField([('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='quote',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='quote_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='quote_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='case_study',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='case_study_en',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='case_study_pl',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='tools',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='tools_en',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())])))], null=True),
        ),
        migrations.AddField(
            model_name='specializationpage',
            name='tools_pl',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())])))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='how_we_work',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))]),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='how_we_work_en',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='how_we_work_pl',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True),
        ),
    ]
