# Generated by Django 2.2.1 on 2019-06-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('projects', '0008_auto_20190603_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Brief name of the project', max_length=32),
        ),
    ]
