# Generated by Django 2.2.2 on 2019-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190614_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Krótka nazwa projektu', max_length=32),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='long_description',
            field=models.CharField(help_text='Bardziej wyczerpujący opis widoczny na Home Page', max_length=516),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='long_description_en',
            field=models.CharField(help_text='Bardziej wyczerpujący opis widoczny na Home Page', max_length=516, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='long_description_pl',
            field=models.CharField(help_text='Bardziej wyczerpujący opis widoczny na Home Page', max_length=516, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description',
            field=models.CharField(help_text='Opis pokazywany na stronie TeamIndex.', max_length=128),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description_en',
            field=models.CharField(help_text='Opis pokazywany na stronie TeamIndex.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description_pl',
            field=models.CharField(help_text='Opis pokazywany na stronie TeamIndex.', max_length=128, null=True),
        ),
    ]
