# Generated by Django 2.2.2 on 2019-06-18 08:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190617_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializationpage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='short_description_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='short_description_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
