# Generated by Django 2.2.3 on 2019-07-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('projects', '0016_auto_20190625_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpage',
            name='phone_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
