# Generated by Django 2.2.3 on 2019-07-05 13:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190705_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html'), template='projects/blocks/tiles_list_with_arrows.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study_en',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html'), template='projects/blocks/tiles_list_with_arrows.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study_pl',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html'), template='projects/blocks/tiles_list_with_arrows.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='tools',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())]), template='projects/blocks/tiles_list_tight.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='tools_en',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())]), template='projects/blocks/tiles_list_tight.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='tools_pl',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())]), template='projects/blocks/tiles_list_tight.html'))], null=True),
        ),
    ]
