# Generated by Django 2.2.3 on 2019-07-08 11:02

from django.db import migrations
import src.apps.main.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20190708_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='process',
            field=wagtail.core.fields.StreamField([('tiles_list', src.apps.main.blocks.HorizontalListWithArrows(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html')))], null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='process_en',
            field=wagtail.core.fields.StreamField([('tiles_list', src.apps.main.blocks.HorizontalListWithArrows(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html')))], null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='process_pl',
            field=wagtail.core.fields.StreamField([('tiles_list', src.apps.main.blocks.HorizontalListWithArrows(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html')))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', src.apps.main.blocks.HorizontalListWithArrows(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html')))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study_en',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', src.apps.main.blocks.HorizontalListWithArrows(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html')))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study_pl',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', src.apps.main.blocks.HorizontalListWithArrows(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], template='main/blocks/tile_fancy_uppercase.html')))], null=True),
        ),
    ]
