# Generated by Django 2.2.3 on 2019-07-09 07:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20190708_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='quote_author',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='quote',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
