# Generated by Django 2.2.2 on 2019-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190614_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='consent_required',
            field=models.BooleanField(default=False, help_text='whether this document is linked in consent checkbox under the contact form'),
            preserve_default=False,
        ),
    ]
