# Generated by Django 2.2.2 on 2019-06-17 10:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_infopage_consent_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='partners',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='partners_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='partners_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
