# Generated by Django 2.2.2 on 2019-06-24 08:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('main', '0015_auto_20190617_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobofferpage',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='jobofferindexpage',
            name='recruitment',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))]),
        ),
        migrations.AlterField(
            model_name='jobofferindexpage',
            name='recruitment_en',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='jobofferindexpage',
            name='recruitment_pl',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
    ]
