# Generated by Django 2.2.2 on 2019-07-01 08:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('main', '0017_auto_20190627_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_body', wagtail.core.fields.RichTextField()),
                ('condition_body_pl', wagtail.core.fields.RichTextField(null=True)),
                ('condition_body_en', wagtail.core.fields.RichTextField(null=True)),
                ('after_send_text', wagtail.core.fields.RichTextField()),
                ('after_send_text_pl', wagtail.core.fields.RichTextField(null=True)),
                ('after_send_text_en', wagtail.core.fields.RichTextField(null=True)),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form', to='wagtailcore.Site')),
            ],
        ),
    ]
