# Generated by Django 2.2.3 on 2019-07-09 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0021_auto_20190708_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='OldHomePage',
        ),
    ]
