# Generated by Django 2.2.3 on 2019-07-09 13:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('main', '0022_auto_20190709_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('rnd', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.CharBlock())])), ('triptych', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('tiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('page', wagtail.core.blocks.PageChooserBlock())])))])), ('hero_carousel', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('tiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('page', wagtail.core.blocks.URLBlock()), ('secondary_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True)),
                ('content_pl', wagtail.core.fields.StreamField([('rnd', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.CharBlock())])), ('triptych', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('tiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('page', wagtail.core.blocks.PageChooserBlock())])))])), ('hero_carousel', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('tiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('page', wagtail.core.blocks.URLBlock()), ('secondary_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True)),
                ('content_en', wagtail.core.fields.StreamField([('rnd', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.CharBlock())])), ('triptych', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('tiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('page', wagtail.core.blocks.PageChooserBlock())])))])), ('hero_carousel', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('tiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=False)), ('page', wagtail.core.blocks.URLBlock()), ('secondary_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
