# Generated by Django 2.2.3 on 2019-07-18 08:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190716_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='condition_body',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='condition_body_en',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='condition_body_pl',
        ),
        migrations.AddField(
            model_name='contactform',
            name='recruitment_terms_accepted_label',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactform',
            name='recruitment_terms_accepted_label_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='recruitment_terms_accepted_label_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='terms_accepted_label',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactform',
            name='terms_accepted_label_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='terms_accepted_label_pl',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
