# Generated by Django 2.2.3 on 2019-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190718_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpagemetric',
            name='property_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='subpagemetric',
            name='property_name_en',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='subpagemetric',
            name='property_name_pl',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
