# Generated by Django 2.2.1 on 2019-05-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190515_1207'),
        ('projects', '0002_projectmetric_specializationindexpage'),
    ]

    operations = [
    ]
