# Generated by Django 2.2.1 on 2019-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190520_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='self_initiated',
            field=models.BooleanField(default=False),
        ),
    ]
