# Generated by Django 2.2.1 on 2019-05-29 09:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('projects', '0005_projectpage_self_initiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('who_we_are', wagtail.core.fields.RichTextField()),
                ('who_we_are_pl', wagtail.core.fields.RichTextField(null=True)),
                ('who_we_are_en', wagtail.core.fields.RichTextField(null=True)),
                ('our_values', wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))])),
                ('our_values_pl', wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True)),
                ('our_values_en', wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock()), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=516)),
                ('description_pl', models.CharField(max_length=516, null=True)),
                ('description_en', models.CharField(max_length=516, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMemberSpecializationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='projects.TeamMember')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_teammemberspecializationtag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='specializations',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='projects.TeamMemberSpecializationTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
