# Generated by Django 2.2.1 on 2019-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_teammember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='description_pl',
        ),
        migrations.AddField(
            model_name='teammember',
            name='long_description',
            field=models.CharField(default='', help_text='More comprehensive description visible on Home Page', max_length=516),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='long_description_en',
            field=models.CharField(help_text='More comprehensive description visible on Home Page', max_length=516, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='long_description_pl',
            field=models.CharField(help_text='More comprehensive description visible on Home Page', max_length=516, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_description',
            field=models.CharField(default='', help_text='Description shown on TeamIndex page.', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_description_en',
            field=models.CharField(help_text='Description shown on TeamIndex page.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_description_pl',
            field=models.CharField(help_text='Description shown on TeamIndex page.', max_length=128, null=True),
        ),
    ]
