# Generated by Django 2.2.2 on 2019-06-17 10:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190617_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study_en',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='case_study_pl',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='projects/blocks/heading.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='how_we_work',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))]),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='how_we_work_en',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='how_we_work_pl',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock(template='projects/blocks/paragraph.html')), ('tiles_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='tools',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='tools_en',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
        migrations.AlterField(
            model_name='specializationpage',
            name='tools_pl',
            field=wagtail.core.fields.StreamField([('tiles_with_description_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())]), template='projects/blocks/tiles_list.html'))], null=True),
        ),
    ]
