# Generated by Django 2.2.3 on 2019-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190705_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='masonry_featured_mobile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
