# Generated by Django 2.2.3 on 2019-07-05 12:40

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectpage_masonry_featured_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='topics',
        ),
        migrations.AddField(
            model_name='topicpage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='topics', to='projects.ProjectPage'),
        ),
    ]
