# Generated by Django 2.2.6 on 2021-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190709_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Brief name of the project', max_length=32),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='long_description',
            field=models.CharField(help_text='More comprehensive description visible on Home Page', max_length=516),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='long_description_en',
            field=models.CharField(help_text='More comprehensive description visible on Home Page', max_length=516, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='long_description_pl',
            field=models.CharField(help_text='More comprehensive description visible on Home Page', max_length=516, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description',
            field=models.CharField(help_text='Description shown on TeamIndex page.', max_length=128),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description_en',
            field=models.CharField(help_text='Description shown on TeamIndex page.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description_pl',
            field=models.CharField(help_text='Description shown on TeamIndex page.', max_length=128, null=True),
        ),
    ]
